### ISSUE TITLE
wont check names

### ISSUE THREAD

**Issue by paired** [GhostTypes/MC-NameChecker#1]
I don't know if its me or something but the proxies count goes to 999 and doesn't check anything.

**Comment by GhostTypes** [comment]
> I don't know if its me or something but the proxies count goes to 999 and doesn't check anything. 

How long are u waiting after the proxies go down to 999? And how many threads did you try. It can take a bit to start up, it's just removing bad proxies and the limit for that is 999.

**Comment by paired** [comment]
i wait like 10 seconds for a small user list and 5 for a large one. i tried all different amounts of threads, (200, 100, 50, 10) nothing works for me

**Comment by GhostTypes** [comment]
Add me on Discord (NotGhostTypes#0872) and I'll help you troubleshoot. It's probably just you not waiting long enough for it to start (can take about 20-30 seconds even for small lists)

**Comment by paired** [comment]
your dc isnt working. add mine: vibrant#2829

**Comment by GhostTypes** [comment]
Issue Resolved, PySocks installation is required
